name: Unit Tests

# Triggers on push or pull request to any branch, and allows manual execution via workflow_dispatch.
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Linux system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxi6 libxcursor1 libxrandr2 libxinerama1 libwayland-client0 libwayland-cursor0 libxkbcommon0 xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Simulation & Graphics Unit Tests
      run: |
        xvfb-run python -m unittest discover -s "Unit tests" -p "test_*.py"
